no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      acceptedaudience: ${AZURE_APP_CLIENT_ID}

forms-api:
  azure:
    groups:
      user-group-id: ${FORMS_API_AD_GROUP_USER}
      admin-group-id: ${FORMS_API_AD_GROUP_ADMIN}
