apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: forms-api
  namespace: fyllut-sendinn
spec:
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  image: {{ image }}
  port: 8082
  replicas:
    max: 4
    min: 2
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 2048Mi
  liveness:
    path: /internal/health/isAlive
    initialDelay: 30
  readiness:
    path: /internal/health/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
        {{#each azure.ad_groups}}
          - id: "{{this.id}}"
        {{/each}}
        extra:
          - NAVident
    sidecar:
      enabled: true
  accessPolicy:
    inbound:
      rules:
      {{#each accessPolicy.inbound.rules}}
        - application: "{{this.application}}"
          namespace: "{{this.namespace}}"
      {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: {{ database.tier }}
        diskType: SSD
        highAvailability: true
        diskAutoresize: true
        databases:
          - name: {{ database.name }}
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-Xms1g -XX:MaxRAMPercentage=80"
    - name: SPRING_PROFILES_ACTIVE
      value: {{ spring-profiles-active }}
    {{#each azure.ad_groups}}
    - name: "FORMS_API_AD_GROUP_{{this.type}}"
      value: "{{this.id}}"
    {{/each}}
