openapi: 3.0.3
info:
  description: CRUD for skjemadefinisjoner, oversettelser og mottaksadresser
  version: 1.0.1
  title: forms-api
  contact:
    name: team-fyllut-sendinn
    url: https://nav-it.slack.com/archives/C04J0SGHQTD
  license:
    name: MIT License
    url: https://github.com/navikt/forms-api/blob/main/LICENSE.md
tags:
  - name: recipients
    description: Adresse for mottaker for en søknad som sendes inn på papir. Settes på førstesiden.
  - name: health
    description: Endepunkter for helsesjekk av applikasjonen.
  - name: edit-global-translations
    description: Vedlikehold av globale oversettelser

paths:
  /v1/recipients:
    $ref: "./recipients/recipients.yaml"

  /v1/recipients/{recipientId}:
    $ref: "./recipients/recipient.yaml"

  /internal/health/isAlive:
    $ref: "./health/is_alive.yaml"

  /internal/health/isReady:
    $ref: "./health/is_ready.yaml"

  /v1/global-translations:
    $ref: "./global-translations/global_translations.yaml"

  /v1/global-translations/{id}:
    $ref: "./global-translations/global_translation.yaml"

  /v1/global-translations/publish:
    $ref: "./global-translations/publish_global_translations.yaml"

  /v1/published-global-translations/{languageCode}:
    $ref: "./global-translations/published_global_translations.yaml"

  /v1/forms/{formPath}/translations:
    $ref: "./form-translations/form-translations.yaml"

  /v1/forms/{formPath}/translations/{id}:
    $ref: "./form-translations/form-translation.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: "http"
      scheme: "bearer"
  schemas:
    UUID:
      type: string
      description: A Universally Unique Identifier
      example: 92ee15dd-dc49-4c95-b9b6-6224bae088bb
    UserId:
      type: string
      example: Navnesen, Navn
      description: Navn på en bruker
    ErrorResponseDto:
      type: object
      description: Informasjon om hva som gikk galt
      required:
      - errorMessage
      properties:
        errorMessage:
          type: string
          example: Resource not found
        correlationId:
          $ref: "#/components/schemas/UUID"
