openapi: 3.0.3
info:
  description: CRUD for skjemadefinisjoner, oversettelser og mottaksadresser
  version: 1.0.1
  title: forms-api
  contact:
    name: team-fyllut-sendinn
    url: https://nav-it.slack.com/archives/C04J0SGHQTD
  license:
    name: MIT License
    url: https://github.com/navikt/forms-api/blob/main/LICENSE.md
tags:
  - name: recipients
    description: Adresse for mottaker for en søknad som sendes inn på papir. Settes på førstesiden.
  - name: health
    description: Endepunkter for helsesjekk av applikasjonen.
  - name: edit-global-translations
    description: Vedlikehold av globale oversettelser
  - name: edit-form-translations
    description: Vedlikehold av oversettelser knyttet til et skjema
  - name: publish-global-translations
    description: Endepunkter for publisering av globale oversettelser
  - name: edit-forms
    description: Vedlikehold av skjemadefinisjoner
  - name: form-publications
    description: Publisering av skjemadefinisjoner

paths:
  /v1/recipients:
    $ref: "./recipients/recipients.yaml"

  /v1/recipients/{recipientId}:
    $ref: "./recipients/recipient.yaml"

  /internal/health/isAlive:
    $ref: "./health/is_alive.yaml"

  /internal/health/isReady:
    $ref: "./health/is_ready.yaml"

  /v1/forms:
    $ref: "./forms/forms.yaml"

  /v1/forms/{formPath}:
    $ref: "./forms/form.yaml"

  /v1/form-publications:
    $ref: "./forms/form-publications.yaml"

  /v1/form-publications/{formPath}:
    $ref: "./forms/form-publication.yaml"

  /v1/global-translations:
    $ref: "./global-translations/global_translations.yaml"

  /v1/global-translations/{id}:
    $ref: "./global-translations/global_translation.yaml"

  /v1/global-translations/publish:
    $ref: "./global-translations/publish_global_translations.yaml"

  /v1/published-global-translations/{languageCode}:
    $ref: "./global-translations/published_global_translations_lang.yaml"

  /v1/published-global-translations:
    $ref: "./global-translations/published_global_translations.yaml"

  /v1/forms/{formPath}/translations:
    $ref: "./form-translations/form-translations.yaml"

  /v1/forms/{formPath}/translations/{id}:
    $ref: "./form-translations/form-translation.yaml"
