name: Deploy alerts

on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts/**'
      - '.github/workflows/alerts-deploy.yaml'

permissions:
  id-token: write

jobs:
  dev-deploy:
    name: Deploy alerts to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts/alerts.yaml
          VARS: .nais/alerts/vars-dev.yaml

#  prod-deploy:
#    name: Deploy alerts to prod
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Deploy to prod
#        uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: prod-gcp
#          RESOURCE: .nais/alerts/alerts.yaml
#          VARS: .nais/alerts/vars-prod.yaml
