name: Build and test
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/**.md'
      - '.nais/alerts/**'
      - '.github/workflows/alerts-deploy.yaml'

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Oslo"
      - name: Build project and run tests
        run: mvn install
      - name: Build and push Docker image
        if: github.ref_name == 'main'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: fyllut-sendinn
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
        image: ${{ steps.docker-build-push.outputs.image }}

  deploy-to-prod:
    name: Deploy to prod
    needs: [build-and-push]
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app.yaml
          VARS: .nais/vars-prod.yaml
          VAR: image=${{needs.build-and-push.outputs.image}}
