name: Build and test
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/**.md'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Build project and run tests
        run: mvn install
